#!/system/bin/sh
#
# load adbd during first boot if property is set

FIRSTBOOT=`getprop persist.service.adb.firstboot`
LOAD_ADBD=`getprop persist.service.adb.enable`
USB_LINK=`cat /sys/class/power_supply/usb/online`

if [ "$FIRSTBOOT $LOAD_ADBD $USB_LINK" -eq "1 1 1" ]; then

    setprop persist.service.adb.firstboot 0

    echo charge_adb > /dev/usb_device_mode

    # set initial state for usb.apk
    echo usb_mode_charge_adb > /tmp/usbd_current_state
    chmod 666 /tmp/usbd_current_state
fi

