#!/system/bin/sh
#
# load adbd during boot if property is set

LOAD_ADBD=`getprop persist.service.adb.enable`
USB_LINK=`cat /sys/class/power_supply/usb/online`

if [ "$USB_LINK $LOAD_ADBD" = "1 1" ]; then

    if [ -f /system/firstboot ]; then

        echo charge_adb > /dev/usb_device_mode

        # set initial state for usb.apk
        echo usb_mode_charge_adb > /tmp/usbd_current_state
        chmod 666 /tmp/usbd_current_state

        rm -f /system/firstboot

    fi
fi

